// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Xx8bpTNCR8kDfrQWee4bn3wnlDo5RJ8',
    appId: '1:319607339404:web:b1fc391b6f28dbeaf3fea9',
    messagingSenderId: '319607339404',
    projectId: 'poetry-735b0',
    authDomain: 'poetry-735b0.firebaseapp.com',
    storageBucket: 'poetry-735b0.appspot.com',
    measurementId: 'G-JRZCH9H35Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NOky84GluJN5dBsLr8yo7N0cPGhOJQU',
    appId: '1:319607339404:android:2ca9e9bf2bfe18d8f3fea9',
    messagingSenderId: '319607339404',
    projectId: 'poetry-735b0',
    storageBucket: 'poetry-735b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8Nl9uVr6P6ELWciMvb_HTOSUCaBZkkI',
    appId: '1:319607339404:ios:7efaff12813cd089f3fea9',
    messagingSenderId: '319607339404',
    projectId: 'poetry-735b0',
    storageBucket: 'poetry-735b0.appspot.com',
    iosClientId: '319607339404-ogd8jf54kr0dnidum3tnhpl0764ego3j.apps.googleusercontent.com',
    iosBundleId: 'com.hymn.flutterPoetry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8Nl9uVr6P6ELWciMvb_HTOSUCaBZkkI',
    appId: '1:319607339404:ios:b89aa9647f85a890f3fea9',
    messagingSenderId: '319607339404',
    projectId: 'poetry-735b0',
    storageBucket: 'poetry-735b0.appspot.com',
    iosClientId: '319607339404-ft34mr6gc6ra51os8641ap3ghgeunk9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPoetry',
  );
}
