// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKu69_W8xSQ4WjBcejlLzMvWeaPWF4l_g',
    appId: '1:917056923195:web:7f022e1a87d7322b49de1e',
    messagingSenderId: '917056923195',
    projectId: 'fcmflutterpoetry-95547',
    authDomain: 'fcmflutterpoetry-95547.firebaseapp.com',
    storageBucket: 'fcmflutterpoetry-95547.appspot.com',
    measurementId: 'G-W791JBES5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHIRDF2g6ZQoazgluPy7SNtUh-R79Dy0',
    appId: '1:917056923195:android:a8d2f61bb06af13149de1e',
    messagingSenderId: '917056923195',
    projectId: 'fcmflutterpoetry-95547',
    storageBucket: 'fcmflutterpoetry-95547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yA7dp-ztvVwRMWVAXz_ODnJKMMbjx_4',
    appId: '1:917056923195:ios:6357fcfaefdcd48749de1e',
    messagingSenderId: '917056923195',
    projectId: 'fcmflutterpoetry-95547',
    storageBucket: 'fcmflutterpoetry-95547.appspot.com',
    iosClientId: '917056923195-504t4s1es6i0r2g88eo6dmefo7ms3ika.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPoetry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8yA7dp-ztvVwRMWVAXz_ODnJKMMbjx_4',
    appId: '1:917056923195:ios:6357fcfaefdcd48749de1e',
    messagingSenderId: '917056923195',
    projectId: 'fcmflutterpoetry-95547',
    storageBucket: 'fcmflutterpoetry-95547.appspot.com',
    iosClientId: '917056923195-504t4s1es6i0r2g88eo6dmefo7ms3ika.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPoetry',
  );
}
